### ISSUE TITLE
Not working with xcode7 (and swift 2)

### ISSUE THREAD

**Issue by craigpearce5** [danielsaidi/AutoSizeTableView#2]
Xcode is throwing some errors regarding the pod files.  `pod install` and `pod update` do not get rid of the error.  Terminal is saying `[!] Unable to find a target named ``DemoTests`` for both.

**Comment by danielsaidi** [comment]
Oh, sorry about that (and sorry for the slow reply). The problem was in the Podfile, which had a reference to a test project that I removed a while back. I have fixed it now.
